# -*- coding: utf-8 -*-
"""IcecreamParlorApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BleBUSq3PQxlO_6JErJ0git8ND1kaAId
"""

import sqlite3

# Database setup
DATABASE = "ice_cream.db"

def create_tables():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()

# Create tables
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS seasonal_flavors (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        flavor_name TEXT NOT NULL,
        season TEXT NOT NULL
    )''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS ingredient_inventory (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ingredient_name TEXT NOT NULL,
        quantity INTEGER NOT NULL
    )''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS customer_feedback (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        suggestion TEXT NOT NULL,
        allergens TEXT
    )''')

    conn.commit()
    conn.close()

# Helper functions
def add_flav(flavor_name, season):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("INSERT INTO seasonal_flavors (flavor_name, season) VALUES (?, ?)", (flavor_name, season))
    conn.commit()
    conn.close()

def search_flav(keyword):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM seasonal_flavors WHERE flavor_name LIKE ?", (f"%{keyword}%",))
    results = cursor.fetchall()
    conn.close()
    return results

def add_suggestion(suggestion, allergens):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("INSERT INTO customer_feedback (suggestion, allergens) VALUES (?, ?)", (suggestion, allergens))
    conn.commit()
    conn.close()

def display_flavs():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM seasonal_flavors")
    results = cursor.fetchall()
    conn.close()
    return results

# Main menu
def main():
    create_tables()

    while True:
        print("\n ICE CREAM PARLOR")
        print("1. Add Seasonal Flavor")
        print("2. Search Flavors")
        print("3. Display All Flavors")
        print("4. Add Customer Suggestion")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            flavor_name = input("Enter flavor name: ")
            season = input("Enter season: ")
            add_flav(flavor_name, season)
            print("Flavor added successfully!")

        elif choice == "2":
            keyword = input("Enter keyword to search: ")
            results = search_flav(keyword)
            if results:
                print("\nSearch Results:")
                for row in results:
                    print(f"ID: {row[0]}, Flavor: {row[1]}, Season: {row[2]}")
            else:
                print("No flavors found!")

        elif choice == "3":
            flavors = display_flavs()
            print("\nAvailable Flavors:")
            for row in flavors:
                print(f"ID: {row[0]}, Flavor: {row[1]}, Season: {row[2]}")

        elif choice == "4":
            suggestion = input("Enter your flavor suggestion: ")
            allergens = input("Enter any allergens (optional): ")
            add_suggestion(suggestion, allergens)
            print("Suggestion submitted successfully!")

        elif choice == "5":
            print("Exiting the application. Have a great Day :))")
            break

        else:
            print("Invalid choice! Please try again.")

if __name__ == "__main__":
    main()